<?php
//  Copyright 2008 Mahesh Asolkar
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

//
// Personalized OnlyBlog Configuration
//
$__config['blog_name']          = 'The OnlyBlog Blog!';
$__config['blog_data_dir']      = 'data';
$__config['owner_name']         = 'Mahesh Asolkar';
$__config['owner_email']        = 'mahesh@mahesha.com';

$__config['theme_dir']          = 'serene';

// $__config['transform_text']     = 0;
?>
