<?php
//  Copyright 2008 Mahesh Asolkar
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

//
// Personalized OnlyBlog Configuration
//
$__config['blog_name']          = 'Name of you blog';
$__config['blog_tag_line']      = 'Tag line for your blog';
$__config['blog_data_dir']      = 'data';
$__config['owner_name']         = 'Your Name';
$__config['owner_email']        = 'your_email@your_host';
$__config['blog_url']           = 'http://blog/url/';

$__config['theme_dir']          = 'serene';

// $__config['transform_text']     = 0;

//
// Comments via IntenseDebate : http://intensedebate.com/
//
$__config['intensedebate_blog_acct']   = 'somehexkey';
?>
